---
- hosts: localhost
  become: true

  tasks:

    - name: required packages installed
      apt:
        name="{{ item }}"
        state=present
        update_cache=yes
      with_items:
        - vim
        - zsh
        - wget
        - git
        - curl
        - libc++-dev
        - cmake
        - g++
        - doxygen
        - sudo
        - openssh-server

    - name: sshd required directory created
      file:
        name: /var/run/sshd
        state: directory

    - name: development user group created
      group:
        name: vagrant
        state: present

    - name: development user created
      user:
        name: vagrant
        group: vagrant
        password: vagrant
        shell: /bin/zsh

    - name: admin connection privilige granted to dev user
      lineinfile:
        path: /etc/sudoers
        line: 'vagrant ALL=(ALL) ALL'

    - name: dev user allowed to ssh
      shell: echo 'vagrant:vagrant' | chpasswd

    - name: oh-my-zsh for zsh customization cloned
      git:
        repo=git://github.com/robbyrussell/oh-my-zsh.git
        dest=/home/vagrant/.oh-my-zsh

    - name: custom zsh configuration copied
      command: cp /home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template /home/vagrant/.zshrc

    - name: vim pathogen directories created
      file: path={{ item }} state=directory
      with_items:
       - /home/vagrant/.vim/autoload
       - /home/vagrant/.vim/bundle
       - /home/vagrant/.vim/plugin

    - name: vim pathogen installed
      shell: curl -LSso /home/vagrant/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

    - name: vim syntastic installed
      git:
        repo=https://github.com/scrooloose/syntastic.git
        dest=/home/vagrant/.vim/bundle/syntastic
        clone=yes

    - name: vim configuration copied
      copy:
        src=roles/vim/files/vimrc
        dest=/home/vagrant/.vimrc

    # TODO: #21 check if it can be removed

    - name: git email configured
      shell: git config --global user.email "docker-cpp-dev@host.com"

    - name: git name configured
      shell: git config --global user.name "docker-cpp-dev"
